index-dir = "/home/robert/projects/find-cmdlet/fc-index-2020-06-23-v2"
web-root = "/home/robert/projects/find-cmdlet/find-cmdlet-web"
listen-addr = "127.0.0.1:8080"

[headers]
Content-Security-Policy = "default-src 'none'; script-src 'self'; style-src 'self'; img-src 'self'; connect-src 'self'; font-src 'none'; object-src 'none'; media-src 'none'; frame-src 'none'; child-src 'none'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'; worker-src 'none';"
Feature-Policy = "accelerometer 'none'; ambient-light-sensor 'none'; autoplay 'none'; battery 'none'; camera 'none'; display-capture 'none'; document-domain 'none'; encrypted-media 'none'; fullscreen 'none'; geolocation 'none'; gyroscope 'none'; legacy-image-formats 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; oversized-images 'none'; payment 'none'; sync-xhr 'none'; unoptimized-images 'none'; unsized-media 'none'; usb 'none'; wake-lock 'none'; xr-spatial-tracking 'none';"
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"