 - name: Set permissions for /etc/ssh
   file:
       path: /etc/ssh
       mode: '0600'

 - name: Deactivate short Diffie-Hellmann moduli for SSH
   shell: "awk '$5 < 3071 { any = 1 } END { exit any }' /etc/ssh/moduli || (awk '$5 >= 3071' /etc/ssh/moduli > /etc/ssh/moduli.tmp && mv /etc/ssh/moduli.tmp /etc/ssh/moduli && echo done)"
   register: deactivated
   changed_when: "'done' in deactivated.stdout"

 - name: Harden sshd config
   copy:
       src: sshd_config
       dest: /etc/ssh/sshd_config
       owner: root
       group: root
       mode: '0644'
   notify:
       restart sshd

