[package]
name = "find-cmdlet-index"
version = "0.1.0"
authors = ["Robert Clipsham <robert@octarineparrot.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tantivy = "0.12.0"
voca_rs = "1.10.0"
